"""Compare PVDAQ CSV files in data/raw and recommend a system_id to focus on."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.data.pvdaq import (  # noqa: E402
    compute_facility_stats,
    load_all_raw_csvs,
    score_facility,
)


def main() -> None:
    raw_dir = ROOT / "data" / "raw"
    frames = load_all_raw_csvs(raw_dir)
    if not frames:
        print(f"No CSV files found in {raw_dir}. See data/raw/README.md.")
        sys.exit(1)

    rows = []
    for sid, df in frames.items():
        stats = compute_facility_stats(df)
        rows.append((sid, stats, score_facility(stats)))

    rows.sort(key=lambda x: x[2], reverse=True)
    print("system_id\tscore\trows\tspan_days\tpct_missing_target\tlongest_gap_h")
    for sid, stats, sc in rows:
        span = 0.0
        if stats.time_start and stats.time_end:
            span = (stats.time_end - stats.time_start).total_seconds() / 86400.0
        print(
            f"{sid}\t{sc:.4f}\t{stats.row_count}\t{span:.1f}\t"
            f"{stats.pct_missing_target:.2f}\t{stats.longest_gap_hours}"
        )

    best_sid, best_stats, best_score = rows[0]
    out = ROOT / "config" / "selected_facility.yaml"
    text = (
        f"# Auto-generated by scripts/compare_pvdaq_facilities.py\n"
        f"system_id: {best_sid}\n"
        f"score: {best_score}\n"
        f"row_count: {best_stats.row_count}\n"
        f"pct_missing_target: {best_stats.pct_missing_target}\n"
        f"notes: \"Data-driven pick: highest score among CSVs in data/raw\"\n"
    )
    out.write_text(text, encoding="utf-8")
    print(f"\nWrote recommended facility to {out}")


if __name__ == "__main__":
    main()
